name: continuous publish
on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

            - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
              with:
                  node-version: 24.x
            - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
              with:
                  version: 11

            - name: Install dependencies
              run: pnpm install

            - name: Build
              run: pnpm build

            - run: pnpx pkg-pr-new publish --compact --no-template
